I"
<h2 id="example-1">Example 1</h2>
<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>#include &lt;iostream&gt;
#include &lt;string&gt;
using namespace std;

void mightGoWrong() {

	bool error1 = false;
	bool error2 = true;

	if(error1) {
		throw "Something went wrong.";
	}

	if(error2) {
		//throw string("Something else went wrong.");
		throw int ("4");
	}

}

void usesMightGoWrong() {
	mightGoWrong();
}



int main() {

	try {
		usesMightGoWrong();
	}
	catch(int e) { // the throwing the value catched and apply to "int e"
		cout &lt;&lt; "Error code: " &lt;&lt; e &lt;&lt; endl;
	}
	catch(char const * e) { // character, so it save one by one alpabet in one matrix place
		cout &lt;&lt; "Error message: " &lt;&lt; e &lt;&lt; endl;
	}
	catch(string &amp;e) { // c++ does not gracefully handle situation where there are two exceptions active at the same time in string.
	    //it imeediatley terminates the program without calling any destructor
		cout &lt;&lt; "string error message: " &lt;&lt; e &lt;&lt; endl;
	}

	cout &lt;&lt; "Still running" &lt;&lt; endl;

	return 0;
}

</code></pre></div></div>

<p><a href="https://postimg.cc/GBW2PrJ0"><img src="https://i.postimg.cc/DZZXTwSz/2321.png" width="700px" title="source: imgur.com" /><a></a></a></p>
:ET